name: angersmap_data
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '^3.8.0'


dependencies:
  archive: ^4.0.7
  crypto: ^3.0.6
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  path: ^1.9.1
  supabase: ^2.9.1

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  flutter_lints: ^6.0.0
